/**
 * Build task that regenerates the translation review sheets in
 * /docs/translations from the live library, so that what a reviewer sees is
 * exactly what Chrono produces.
 *
 * Run with: box task run TranslationDocs
 *
 */
component {

	property name="print" inject="PrintBuffer";

	variables.languageNames = {
		  en = "English"
		, de = "German"
		, el = "Greek"
		, es = "Spanish"
		, fr = "French"
		, id = "Indonesian"
		, it = "Italian"
		, ja = "Japanese"
		, ko = "Korean"
		, nl = "Dutch"
		, pl = "Polish"
		, pt = "Portuguese"
		, ro = "Romanian"
		, ru = "Russian"
		, sw = "Swahili"
		, tr = "Turkish"
		, zh = "Chinese (Simplified)"
	};

	/**
	 * Every distinct shape of description the library can produce. Keeping one
	 * sample per branch of Chrono's describe logic means the review sheets
	 * cover the whole surface, not just the common cases.
	 *
	 */
	variables.samples = [
		  { cron="disabled"          , note="scheduling turned off"                          }
		, { cron="* * * * * *"       , note="every second"                                    }
		, { cron="*/10 * * * * *"    , note="stepped seconds"                                 }
		, { cron="0 * * * * *"       , note="every minute"                                    }
		, { cron="0 0 * * * *"       , note="every hour, on the hour"                         }
		, { cron="0 */5 * * * *"     , note="every 5 minutes"                                 }
		, { cron="0 */15 * * * *"    , note="every 15 minutes"                                }
		, { cron="0 */30 * * * *"    , note="every 30 minutes"                                }
		, { cron="0 7 * * * *"       , note="a single minute of every hour"                   }
		, { cron="0 0 */2 * * *"     , note="every 2 hours"                                   }
		, { cron="0 0 */5 * * *"     , note="every 5 hours"                                   }
		, { cron="0 0 0 * * *"       , note="daily, at a fixed time (midnight)"               }
		, { cron="0 30 9 * * *"      , note="daily, at a fixed time (09:30)"                  }
		, { cron="0 0 0 ? * MON"     , note="weekly, on one day, at midnight"                 }
		, { cron="0 0 0 ? * MON,FRI" , note="weekly, on several days, at midnight"            }
		, { cron="0 30 9 ? * FRI"    , note="weekly, on one day, at a time"                   }
		, { cron="0 15 14 ? * MON-FRI", note="weekly, on a range of days, at a time"          }
		, { cron="0 0 0 1 * ?"       , note="monthly, on the 1st (ordinal: 1)"                }
		, { cron="0 0 0 2 * ?"       , note="monthly, on the 2nd (ordinal: 2)"                }
		, { cron="0 0 0 3 * ?"       , note="monthly, on the 3rd (ordinal: 3)"                }
		, { cron="0 0 0 4 * ?"       , note="monthly, on the 4th (ordinal: other)"            }
		, { cron="0 0 0 11 * ?"      , note="monthly, on the 11th (ordinal: teens)"           }
		, { cron="0 0 0 21 * ?"      , note="monthly, on the 21st (ordinal: 21)"              }
		, { cron="0 0 0 */3 * ?"     , note="every 3 days, at midnight"                       }
		, { cron="0 0 0 1 1 ?"       , note="yearly, on a date (January)"                     }
		, { cron="0 0 0 25 12 ?"     , note="yearly, on a date (December)"                    }
		, { cron="0 0 0 1 1,7 ?"     , note="yearly, in several months"                       }
		, { cron="0 0 12 1 * ?"      , note="no phrasing available, falls back to the cron"   }
	];

	function run() {
		var chrono   = new models.Chrono();
		var i18n     = new models.ChronoI18n();
		var locales  = i18n.listLocales();
		var baseLang = i18n.getDefaultLocale();
		var baseKeys = _orderedKeys( i18n.getBundleFile( baseLang ) );
		var docsDir  = getCWD() & "docs/translations/";

		if ( !DirectoryExists( docsDir ) ) {
			DirectoryCreate( docsDir, true );
		}

		for( var locale in locales ) {
			var file = docsDir & locale & ".md";

			FileWrite( file, _renderLanguageDoc(
				  locale   = locale
				, baseLang = baseLang
				, baseKeys = baseKeys
				, chrono   = chrono
				, i18n     = i18n
			), "utf-8" );

			print.line( "wrote docs/translations/#locale#.md" ).toConsole();
		}

		FileWrite( getCWD() & "TRANSLATIONS.md", _renderIndex( locales, baseLang, baseKeys, i18n ), "utf-8" );
		print.line( "wrote TRANSLATIONS.md" ).toConsole();
	}

// PRIVATE
	private string function _renderLanguageDoc( required string locale, required string baseLang, required array baseKeys, required any chrono, required any i18n ) {
		var name  = _languageName( arguments.locale );
		var isNew = arguments.locale == arguments.baseLang;
		var md    = [];

		ArrayAppend( md, "## Chrono descriptions in #name# (`#arguments.locale#`)" );
		ArrayAppend( md, "" );
		ArrayAppend( md, "Generated by `box task run TranslationDocs` — do not edit by hand." );
		ArrayAppend( md, "Edit `i18n/#arguments.locale#.json` and regenerate." );
		ArrayAppend( md, "" );
		ArrayAppend( md, "Every line below is the real output of `describeCronTabExression()`. If a" );
		ArrayAppend( md, "phrase reads badly in #name#, the fix is a template in the bundle — see" );
		ArrayAppend( md, "[TRANSLATIONS.md](../../TRANSLATIONS.md)." );
		ArrayAppend( md, "" );
		ArrayAppend( md, "#### Descriptions" );
		ArrayAppend( md, "" );

		if ( isNew ) {
			ArrayAppend( md, "| Cron expression | Meaning | #name# (`#arguments.locale#`) |" );
			ArrayAppend( md, "| --- | --- | --- |" );
		} else {
			ArrayAppend( md, "| Cron expression | Meaning | #_languageName( arguments.baseLang )# (`#arguments.baseLang#`) | #name# (`#arguments.locale#`) |" );
			ArrayAppend( md, "| --- | --- | --- | --- |" );
		}

		for( var sample in variables.samples ) {
			var translated = arguments.chrono.describeCronTabExression( sample.cron, arguments.locale );
			var row        = "| `#sample.cron#` | #sample.note# |";

			if ( !isNew ) {
				row &= " #arguments.chrono.describeCronTabExression( sample.cron, arguments.baseLang )# |";
			}

			ArrayAppend( md, row & " #translated# |" );
		}

		ArrayAppend( md, "" );
		ArrayAppend( md, "#### Month and day names" );
		ArrayAppend( md, "" );
		ArrayAppend( md, "Held in the bundle as `month_1`...`month_12` and `dow_1`...`dow_7`, seeded" );
		ArrayAppend( md, "from CLDR. Correct them if your language needs a different form here — for" );
		ArrayAppend( md, "example a genitive month name because these only ever appear in a date." );
		ArrayAppend( md, "" );
		ArrayAppend( md, "| | | | | | |" );
		ArrayAppend( md, "| --- | --- | --- | --- | --- | --- |" );

		var monthCells = [];
		for( var m=1; m<=12; m++ ) {
			ArrayAppend( monthCells, arguments.i18n.monthName( m, arguments.locale ) );
		}
		for( var m=1; m<=12; m+=6 ) {
			ArrayAppend( md, "| " & ArrayToList( ArraySlice( monthCells, m, 6 ), " | " ) & " |" );
		}

		ArrayAppend( md, "" );
		ArrayAppend( md, "| | | | | | | |" );
		ArrayAppend( md, "| --- | --- | --- | --- | --- | --- | --- |" );

		var dowCells = [];
		for( var d=1; d<=7; d++ ) {
			ArrayAppend( dowCells, arguments.i18n.dayOfWeekName( d, arguments.locale ) );
		}
		ArrayAppend( md, "| " & ArrayToList( dowCells, " | " ) & " |" );

		ArrayAppend( md, "" );
		ArrayAppend( md, "#### Message templates" );
		ArrayAppend( md, "" );
		ArrayAppend( md, "The raw contents of `i18n/#arguments.locale#.json`. `{1}` and `{2}` are" );
		ArrayAppend( md, "filled in at runtime and must survive translation." );
		ArrayAppend( md, "" );

		var bundle = arguments.i18n.getBundleFile( arguments.locale );
		var base   = arguments.i18n.getBundleFile( arguments.baseLang );

		if ( isNew ) {
			ArrayAppend( md, "| Key | #name# |" );
			ArrayAppend( md, "| --- | --- |" );
		} else {
			ArrayAppend( md, "| Key | #_languageName( arguments.baseLang )# | #name# |" );
			ArrayAppend( md, "| --- | --- | --- |" );
		}

		for( var key in _orderedKeys( bundle ) ) {
			var row = "| `#key#` |";

			if ( !isNew ) {
				row &= " " & ( StructKeyExists( base, key ) ? base[ key ] : "_(not in base bundle)_" ) & " |";
			}

			ArrayAppend( md, row & " #bundle[ key ]# |" );
		}

		ArrayAppend( md, "" );

		return ArrayToList( md, Chr( 10 ) );
	}

	private string function _renderIndex( required array locales, required string baseLang, required array baseKeys, required any i18n ) {
		var md = [];

		ArrayAppend( md, "## Translating Chrono" );
		ArrayAppend( md, "" );
		ArrayAppend( md, "`describeCronTabExression( expression, locale )` turns a cron expression into" );
		ArrayAppend( md, "a human readable phrase. This file explains how those phrases are translated" );
		ArrayAppend( md, "and how to review or add a language." );
		ArrayAppend( md, "" );
		ArrayAppend( md, "#### How it works" );
		ArrayAppend( md, "" );
		ArrayAppend( md, "Chrono does not translate cron descriptions word by word. It recognises the" );
		ArrayAppend( md, "*shape* of an expression and then picks one whole message template for it, so" );
		ArrayAppend( md, "each language controls its own word order rather than inheriting English's." );
		ArrayAppend( md, "" );
		ArrayAppend( md, "* Templates live in `i18n/<locale>.json`, one file per language." );
		ArrayAppend( md, "* `{1}` and `{2}` are placeholders filled in at runtime (a time, a day name," );
		ArrayAppend( md, "  a number). Keep them, and put them where the language needs them — reordering" );
		ArrayAppend( md, "  them is expected and supported." );
		ArrayAppend( md, "* `i18n/#arguments.baseLang#.json` is the base bundle. Any key a language omits" );
		ArrayAppend( md, "  falls back to it, so a partial translation degrades one phrase at a time." );
		ArrayAppend( md, "* A locale is resolved from least to most specific: `pt-BR` is served by" );
		ArrayAppend( md, "  `#arguments.baseLang#.json`, then `pt.json`, then `pt_BR.json`. Both `pt-BR`" );
		ArrayAppend( md, "  and `pt_BR` are accepted." );
		ArrayAppend( md, "* The one exception to that fallback is `ordinal_<n>`. Ordinal rules do not" );
		ArrayAppend( md, "  transfer between languages, so a per-day override is only ever read from the" );
		ArrayAppend( md, "  language's own bundle and never inherited from `#arguments.baseLang#.json`." );
		ArrayAppend( md, "* Month and day names are in the bundles too, as `month_1`...`month_12` and" );
		ArrayAppend( md, "  `dow_1`...`dow_7` (`dow_1` is Sunday). They are shipped as data rather than" );
		ArrayAppend( md, "  read from the engine, because `LSDateFormat()` does not exist on every CFML" );
		ArrayAppend( md, "  engine and Chrono should describe a cron identically everywhere." );
		ArrayAppend( md, "" );
		ArrayAppend( md, "#### Review sheets" );
		ArrayAppend( md, "" );
		ArrayAppend( md, "One page per language, showing the real output for every kind of expression" );
		ArrayAppend( md, "Chrono can describe. These are generated — regenerate them after editing a" );
		ArrayAppend( md, "bundle with:" );
		ArrayAppend( md, "" );
		ArrayAppend( md, "```" );
		ArrayAppend( md, "box task run TranslationDocs" );
		ArrayAppend( md, "```" );
		ArrayAppend( md, "" );

		for( var locale in arguments.locales ) {
			var bundle  = arguments.i18n.getBundleFile( locale );
			var missing = 0;

			for( var key in arguments.baseKeys ) {
				if ( !StructKeyExists( bundle, key ) ) {
					missing++;
				}
			}

			var status = missing ? "#missing# key(s) missing, falling back to `#arguments.baseLang#`" : "complete";

			ArrayAppend( md, "* [#_languageName( locale )# (`#locale#`)](docs/translations/#locale#.md) — #status#" );
		}

		ArrayAppend( md, "" );
		ArrayAppend( md, "#### What to look for when reviewing" );
		ArrayAppend( md, "" );
		ArrayAppend( md, "1. Does each phrase read like something a person would write, in the register" );
		ArrayAppend( md, "   of a UI label? These strings appear in a schedule column, so short is good." );
		ArrayAppend( md, "2. Is the word order right for the language — particularly `month_day`, which" );
		ArrayAppend( md, "   controls whether a date reads as ""January 1st"" or ""1 January""?" );
		ArrayAppend( md, "3. Are the day-of-month ordinals right? `ordinal` is the pattern for every" );
		ArrayAppend( md, "   day, and `ordinal_<n>` overrides a single day where the language is" );
		ArrayAppend( md, "   irregular — French adds `ordinal_1` for ""1er"" and nothing else, English" );
		ArrayAppend( md, "   needs 1, 2, 3, 21, 22, 23 and 31. A language with no ordinals just sets" );
		ArrayAppend( md, "   `ordinal` to `{1}`. Note the same pattern serves both ""on the 1st"" and the" );
		ArrayAppend( md, "   day inside a date, so pick the form that works in both." );
		ArrayAppend( md, "4. Do the plural forms hold up? `every_n_minutes`, `every_n_hours` and" );
		ArrayAppend( md, "   `every_n_days_at_midnight` always receive a number greater than one, so a" );
		ArrayAppend( md, "   language with several plural forms only needs the one that fits 2 and above." );
		ArrayAppend( md, "5. Is `list_separator` right for joining day names (`, ` in most languages," );
		ArrayAppend( md, "   `、` in Japanese and Chinese)?" );
		ArrayAppend( md, "6. Are the month and day names in the right form for appearing inside a date," );
		ArrayAppend( md, "   rather than standing alone?" );
		ArrayAppend( md, "" );
		ArrayAppend( md, "#### Known rough edges in the source phrasing" );
		ArrayAppend( md, "" );
		ArrayAppend( md, "These are awkward in English too, and are inherited from the descriptions the" );
		ArrayAppend( md, "library has always produced. Translate them literally for now rather than" );
		ArrayAppend( md, "improving on them, so that all languages stay in step:" );
		ArrayAppend( md, "" );
		ArrayAppend( md, "* `every_second_at` — ""every second (:*/10)"" leaks cron syntax into the phrase." );
		ArrayAppend( md, "* `minute_past` — ""every minute past 7"" really means ""at 7 minutes past every hour""." );
		ArrayAppend( md, "* `in_months` — combines badly with `month_day`, e.g. ""in 1,7 1st""." );
		ArrayAppend( md, "* `cron_fallback` — used when no phrasing fits; shows the raw expression." );
		ArrayAppend( md, "" );
		ArrayAppend( md, "#### Adding a language" );
		ArrayAppend( md, "" );
		ArrayAppend( md, "1. Copy `i18n/#arguments.baseLang#.json` to `i18n/<code>.json` and translate the values." );
		ArrayAppend( md, "2. Run `box task run TranslationDocs` to generate the review sheet." );
		ArrayAppend( md, "3. Run `./runtests.sh`. The suite checks every bundle against the base key set" );
		ArrayAppend( md, "   and asserts that no placeholder is left unfilled in any locale." );
		ArrayAppend( md, "" );

		return ArrayToList( md, Chr( 10 ) );
	}

	private array function _orderedKeys( required struct bundle ) {
		var keys = StructKeyArray( arguments.bundle );

		ArraySort( keys, "textnocase" );

		return keys;
	}

	private string function _languageName( required string locale ) {
		return StructKeyExists( variables.languageNames, arguments.locale ) ? variables.languageNames[ arguments.locale ] : arguments.locale;
	}

}
